server:
  port: 8080

application:
  name: GidacPoc #@application.name@
  context:
    request:
      requestIdHeader: x-request-id
  run:
    antivirus-scan:
      enabled: 0
    processing:
      enabled: dita
      fs-tree:
        native-tmp: true
        tmp-dir: '/tmp'
      dita:
        embedded-toolkit: true
        toolkit-path: '/home/georgette/Applications/dita-ot-4.0/bin/dita'
      chemistry:
        embedded-toolkit: false
        toolkit-path: '/home/georgette/Applications/oxygen-publishing-engine-3.x/bin/dita'
    java:
      use-embedded: true
      version: '17'

spring:
  security:
    user:
      name: oscar
      password: PhP7vvnPpfN7SC7