server:
  port: 8080

application:
  context:
    request:
      requestIdHeader: x-request-id
  run:
    antivirus-scan:
      enabled: 0
    processing:
      enabled: dita
      fs-tree:
        native-tmp: true
        tmp-dir: ''
      dita:
        embedded-toolkit: true
        toolkit-path: ''
      chemistry: { }
    java:
      use-embedded: true
      version: '17'

spring:
  security:
    user:
      name: oscar
      password: PhP7vvnPpfN7SC7