name: Build application
run-name: Building and testing application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build
        run: ./mvnw --batch-mode --update-snapshots package

      - name: Save Package
        run: |
          mkdir staging && find . -type f -name *SNAPSHOT.jar -exec cp "{}" /staging/. \;

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6